### ISSUE TITLE
[ERROR]	Client discovery failed: Found ALVR client with incompatible version

### ISSUE THREAD

**Issue by zmf2022** [nosix/nreal-alvr#1]
Thanks for sharing ,i'm having a problem, can you help me ?

**Comment by nosix** [comment]
What is this an error when doing?
There is too little information for me to help.

**Comment by zmf1314** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！

**Comment by zmf2022** [comment]
thanks, I have solve this problem by  recompiling the server, but i find another problem, the nreal left eye has no picture.

**Comment by nosix** [comment]
I'm sorry I didn't mention it in the README.
When building the ALVR Android library, the version of `ALVR/alvr/common/Cargo.toml` must be set to `17.0.0`.
I'm trying to find out if there is another better way, so it's not listed.

I don't know the cause of the fact that the left eye is not displayed because it has not occurred in my environment.
I'm using the Nreal Computing Unit to verify.

**Comment by nosix** [comment]
How to draw on both eyes:

1. Generate Texture2D with AlvrStreamTexture class and pass it to ALVR Android library
2. Set the generated Texture2D to L_RawImage and R_RawImage
3. Draw the video of both eyes on Texture2D from the video received from the server with ALVR Android library
4. Display the image of each eye by UV Rect setting of L_RawImage and R_RawImage

**Comment by nosix** [comment]
If one eye is displayed, it is presumed that the image of both eyes is drawn in Texture2D. It may be that only one eye failed to draw in step 4.

**Comment by zmf2022** [comment]
thanks，I have solved my problem.
